// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwWavTtVIW5tehTBuxxwpkq6EZXsY549M',
    appId: '1:165970492693:web:4f3837e673803e5f8ffd1c',
    messagingSenderId: '165970492693',
    projectId: 'modu-calorie',
    authDomain: 'modu-calorie.firebaseapp.com',
    storageBucket: 'modu-calorie.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyqRwszdMHRgX-CDyRfXd1Wf3BwolYQow',
    appId: '1:165970492693:android:6a62854d136c38de8ffd1c',
    messagingSenderId: '165970492693',
    projectId: 'modu-calorie',
    storageBucket: 'modu-calorie.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF9VzKMDlqBkOnCo2n27NIxPh7ls16MnM',
    appId: '1:165970492693:ios:a289c1318f0fc8f38ffd1c',
    messagingSenderId: '165970492693',
    projectId: 'modu-calorie',
    storageBucket: 'modu-calorie.appspot.com',
    iosClientId: '165970492693-91p5glgp6ngs53p11ilmvo2pvm9bak56.apps.googleusercontent.com',
    iosBundleId: 'com.example.moduCalorie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF9VzKMDlqBkOnCo2n27NIxPh7ls16MnM',
    appId: '1:165970492693:ios:a289c1318f0fc8f38ffd1c',
    messagingSenderId: '165970492693',
    projectId: 'modu-calorie',
    storageBucket: 'modu-calorie.appspot.com',
    iosClientId: '165970492693-91p5glgp6ngs53p11ilmvo2pvm9bak56.apps.googleusercontent.com',
    iosBundleId: 'com.example.moduCalorie',
  );
}
